export const typesRef = [
  {
    type: "Water",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/water.svg?raw=true",
    weakness: ["Grass", "Electric"],
    effective: ["Ground", "Rock", "Fire"],
    noteffective: ["Water", "Grass", "Dragon"],
    resist: ["Fire", "Water", "Ice", "Steel"],
    noeffect: [],
    immune: [],
    color: "#539DDF",
  },
  {
    type: "Bug",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/bug.svg?raw=true",
    weakness: ["Fire", "Flying", "Rock"],
    effective: ["Grass", "Psychic", "Dark"],
    noteffective: [
      "Fighting",
      "Flying",
      "Poison",
      "Ghost",
      "Steel",
      "Fire",
      "Fairy",
    ],
    resist: ["Fighting", "Ground", "Grass"],
    noeffect: [],
    immune: [],
    color: "#92BC2C",
  },
  {
    type: "Fire",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/fire.svg?raw=true",
    weakness: ["Ground", "Rock", "Water"],
    effective: ["Grass", "Bug", "Ice", "Steel"],
    noteffective: ["Rock", "Fire", "Water", "Dragon"],
    resist: ["Bug", "Fire", "Grass", "Steel", "Ice", "Fairy"],
    noeffect: [],
    immune: [],
    color: "#EE8130",
  },
  {
    type: "Flying",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/flying.svg?raw=true",
    weakness: ["Electric", "Rock", "Ice"],
    effective: ["Grass", "Bug", "Fighting"],
    noteffective: ["Rock", "Electric", "Steel"],
    resist: ["Bug", "Grass", "Fighting"],
    noeffect: [],
    immune: ["Ground"],
    color: "#A1BBEC",
  },
  {
    type: "Dark",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/dark.svg?raw=true",
    weakness: ["Fighting", "Bug", "Fairy"],
    effective: ["Ghost", "Psychic"],
    noteffective: ["Fighting", "Dark", "Fairy"],
    resist: ["Ghost", "Dark"],
    noeffect: [],
    immune: ["Psychic"],
    color: "#595761",
  },
  {
    type: "Dragon",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/dragon.svg?raw=true",
    weakness: ["Ice", "Dragon", "Fairy"],
    effective: ["Dragon"],
    noteffective: ["Steel"],
    resist: ["Fire", "Water", "Grass", "Electric"],
    noeffect: ["Fairy"],
    immune: [],
    color: "#0C69C8",
  },
  {
    type: "Electric",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/electric.svg?raw=true",
    weakness: ["Ground"],
    effective: ["Flying", "Water"],
    noteffective: ["Electric", "Grass", "Dragon"],
    resist: ["Flying", "Steel", "Electric"],
    noeffect: ["Ground"],
    immune: [],
    color: "#F7D02C",
  },
  {
    type: "Fairy",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/fairy.svg?raw=true",
    weakness: ["Poison", "Steel"],
    effective: ["Fighting", "Dragon", "Dark"],
    noteffective: ["Poison", "Steel", "Fire"],
    resist: ["Fighting", "Bug", "Dark"],
    noeffect: [],
    immune: ["Dragon"],
    color: "#EE90E6",
  },
  {
    type: "Fighting",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/fighting.svg?raw=true",
    weakness: ["Flying", "Psychic", "Fairy"],
    effective: ["Normal", "Rock", "Ice", "Steel", "Dark"],
    noteffective: ["Flying", "Poison", "Bug", "Psychic", "Fairy"],
    resist: ["Rock", "Bug", "Dark"],
    noeffect: ["Ghost"],
    immune: [],
    color: "#C22E28",
  },
  {
    type: "Ghost",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/ghost.svg?raw=true",
    weakness: ["Ghost", "Dark"],
    effective: ["Ghost", "Psychic"],
    noteffective: ["Dark"],
    resist: ["Poison", "Bug"],
    noeffect: ["Normal"],
    immune: ["Normal", "Fighting"],
    color: "#5F6DBC",
  },
  {
    type: "Grass",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/grass.svg?raw=true",
    weakness: ["Flying", "Poison", "Bug", "Fire", "Ice"],
    effective: ["Ground", "Rock", "Water"],
    noteffective: [
      "Flying",
      "Poison",
      "Bug",
      "Fire",
      "Grass",
      "Dragon",
      "Steel",
    ],
    resist: ["Ground", "Water", "Grass", "Electric"],
    noeffect: [],
    immune: [],
    color: "#7AC74C",
  },
  {
    type: "Ground",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/ground.svg?raw=true",
    weakness: ["Water", "Grass", "Ice"],
    effective: ["Poison", "Rock", "Fire", "Electric", "Steel"],
    noteffective: ["Bug", "Grass"],
    resist: ["Poison", "Rock"],
    noeffect: ["Flying"],
    immune: ["Electric"],
    color: "#915121",
  },
  {
    type: "Ice",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/ice.svg?raw=true",
    weakness: ["Fighting", "Rock", "Fire", "Steel"],
    effective: ["Flying", "Ground", "Grass", "Dragon"],
    noteffective: ["Water", "Ice", "Steel", "Fire"],
    resist: ["Ice"],
    noeffect: [],
    immune: [],
    color: "#96D9D6",
  },
  {
    type: "Normal",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/normal.svg?raw=true",
    weakness: ["Fighting"],
    effective: [],
    noteffective: ["Rock", "Steel"],
    resist: [],
    noeffect: ["Ghost"],
    immune: ["Ghost"],
    color: "#A0A29F",
  },
  {
    type: "Poison",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/poison.svg?raw=true",
    weakness: ["Ground", "Psychic"],
    effective: ["Grass", "Fairy"],
    noteffective: ["Poison", "Ground", "Rock", "Ghost"],
    resist: ["Fighting", "Poison", "Grass", "Bug", "Fairy"],
    noeffect: ["Steel"],
    immune: [],
    color: "#B763CF",
  },
  {
    type: "Psychic",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/psychic.svg?raw=true",
    weakness: ["Bug", "Ghost", "Dark"],
    effective: ["Fighting", "Poison"],
    noteffective: ["Psychic", "Steel"],
    resist: ["Fighting", "Psychic"],
    noeffect: ["Dark"],
    immune: [],
    color: "#F95587",
  },
  {
    type: "Rock",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/rock.svg?raw=true",
    weakness: ["Fighting", "Ground", "Water", "Grass", "Steel"],
    effective: ["Flying", "Bug", "Fire", "Ice"],
    noteffective: ["Fighting", "Ground", "Steel"],
    resist: ["Normal", "Flying", "Poison", "Fire"],
    noeffect: [],
    immune: [],
    color: "#C9BB8A",
  },
  {
    type: "Steel",
    svg: "https://github.com/duiker101/pokemon-type-svg-icons/blob/master/icons/steel.svg?raw=true",
    weakness: ["Fighting", "Ground", "Fire"],
    effective: ["Rock", "Fairy", "Ice"],
    noteffective: ["Steel", "Fire", "Water", "Electric"],
    resist: [
      "Normal",
      "Flying",
      "Rock",
      "Bug",
      "Steel",
      "Grass",
      "Psychic",
      "Ice",
      "Dragon",
      "Fairy",
    ],
    noeffect: [],
    immune: ["Poison"],
    color: "#5695A3",
  },
];
